### PR TITLE
Add external-data-checker support

### PR DESCRIPTION
**Pull request by gasinvein**
Flathub now can automate checking for updates https://github.com/flathub/flatpak-external-data-checker

### CODE REVIEW

**Comment by SISheogorath** [comment]
Just being curious, what are the implications of the change?

**Comment by gasinvein** [comment]
As I understand, Flathub bot will start checking for Riot updates in it's deb repo and open a PR if there are any.

**Comment by SISheogorath** [comment]
My interpretation of the Repo's readme is that it's for external data (which is loaded when installing the app).

@barthalion do you have any input here?

**Comment by gasinvein** [comment]
At least when I used it locally it's able to check not only `extra-data` sources, but any `file` and `archive` sources as well.

**Comment by barthalion** [comment]
External data in the tool's name mean literally that – any source fetched externally, binary or not. It doesn't have to be extra-data. If you think you could improve the wording there, please send pull requests as with my non-native English I can't express that well.

(It's true the tool was developed for `extra-data` apps, but I actually plan to add `x-checker-data` to all applications "repackaging" binaries as it's easy win with taking the maintenance burden off.)

**Comment by barthalion** [comment]
Also without `x-checker-data` specified it verifies whether sources are still present and checksums valid, but we're not ready yet to enable that globally.

**Pull request merged**
