### PR TITLE
Update im.riot.Riot.json

### PR DESCRIPTION
**Pull request by liberodark**
Fix https://github.com/flathub/im.riot.Riot/issues/68

### CODE REVIEW

**Comment by SISheogorath** [comment]
No, we are **not going to grant Riot access to the entire host filesystem**.

We allow access to the Downloads directory. If you want your setup to have access to the entire host system, feel free to use `flatpak override im.riot.Riot --filesystem=host`, but we won't use such insecure settings by default.

Also there is currently work coming up that integrates GTK portals into Electron, which will make the download directory permission obsolete. https://github.com/electron/electron/pull/19159

**Comment by liberodark** [comment]
That is better not great to limit upload from just one folder better to add home

**Comment by SISheogorath** [comment]
The reasoning why using download and not home is simple: `echo flatpak run im.riot.Riot >> $HOME/.bashrc` <-- Here you have your sandbox break out.

This could might be mitigated by providing `--filesystem=home:ro` but even then you bring a lot of security concerns to people's desktop: `cat $HOME/.ssh/id_rsa` <-- Oops, someone was able to collect SSH keys with access to production servers.

Keeping it with the Downloads directory is a good idea from a security perspective. Also there is a UX problem when using the home directory read-only: When you get a file in Riot, you can download it. The saving dialog would show the entire home directory as a place to safe it. But only the Downloads directory would be writable. But there is no indicator for that. You only get a permission denied error. Therefore, the Downloads directory is the right way to go here, from a UX and security perspective.

**Comment by SISheogorath** [comment]
Also the discussion is already going on here: https://github.com/flathub/im.riot.Riot/issues/33

If you want to express your concern, there you go, we might find more people with ideas for a solution. :)

**Pull request closed without merging**
