### PR TITLE
Inhibit the screensaver during audio/video calls

### LINKED ISSUE #210: Screen saver inhibition does not work on flatpak version
Hello,

When doing a long video call, the flatpak version of element does not inhibit the screen saver.
It seems the configuration needs `    "--talk-name=org.freedesktop.ScreenSaver"`. See https://github.com/flathub/us.zoom.Zoom/issues/58

### PR DESCRIPTION
**Pull request by daenney**
* Based on https://github.com/flathub/us.zoom.Zoom/pull/179
* Fixes #210

### CODE REVIEW

**Comment by daenney** [comment]
Need to test this once I have a build.

**Review by BEEDELLROKEJULIANLOCKHART — APPROVED** [review]
This is also used at http://github.com/flathub/us.zoom.Zoom/blob/master/us.zoom.Zoom.json, so it is appearing to me to be a necessary improvement.

**Comment by SISheogorath** [comment]
Well, Element isn't Zoom, but using Jitsi. Jitsi also has a desktop client in flathub and sues the following permissions: https://github.com/flathub/org.jitsi.jitsi-meet/blob/7641b06bf098a3c9770d77984b9eb86bb05cd5fe/org.jitsi.jitsi-meet.yaml#L22-L25

But I'm not sure we really want to add all these permissions.

**Comment by daenney** [comment]
Yeah, I saw that. I was going to start with ScreenSaver and see if that's enough for what we want.

* `org.freedesktop.PowerManagement` doesn't seem to exist on my session bus
* `org.gnome.SessionManager` has `Inhibit`, and it's the same thing that `org.freedesktop.ScreenSaver`. The latter sounds more portable, given it's org.freedesktop instead of org.gnome so I'm hoping that's enough to make it work everywhere

**Pull request merged**
