### PR TITLE
element.sh: Add Electron flags for improved UX under Wayland

### PR DESCRIPTION
**Pull request by LorbusChris**

### CODE REVIEW

**Comment by DashieTM** [comment]
Some important things to note.

I understand that previously, the idea was to not deviate from upstream element. 
However, wayland is becoming the norm on big linux distributions and will essentially replace x11 as the default.
With this, we should at least be able to use the application natively on wayland, which is currently locked to users who know exactly how to configure a .desktop file.
This makes the entry on wayland harder for new users, as xwayland was and will never be a proper replacement for native applications. Things like screenshare, scaling, hotkeys, and more features often either do not work at all, or only work partially.

The problem we face with electron is that everyone tries to pass the burden of doing the change upstream.
Since this is a community maintained version of element, the upstream is element. They then pass it to electron, which passes it to chromium.
Problem is that both chromium and electron will not make the change, as linux is only a fraction of their user base, and they have to make sure that basically all apps would still work.
This means that the change **should** happen on element. There is an open thread on element, which sadly lead to nothing.
I am sure it is partially because they are busy doing other things, but it means that **the issue is not being handled**.

When the change is made here, it could fix the issue for the userbase that is directly affected by that issue.
For the other packaging solutions like deb, rpm etc the distributions should put in the flag.

Either way, many thanks for maintaining the flatpak version of element, and of cource Lorbus for this PR.

**Comment by LorbusChris** [comment]
cc @SISheogorath for comment

**Comment by LorbusChris** [comment]
cc @ananace  @TingPing @barthalion

**Comment by ananace** [comment]
It looks reasonable to me, though it will change the window classes and therefore probably cause any user-defined window settings to be reset.
But there's not really much that can be done about that.

**Comment by SISheogorath** [comment]
I'm still not a big fan of doing this differently than upstream. However, I guess we end up with a chicken-egg problem, as in: The defaults won't change because no one uses the new stuff, and the new stuff won't be used due to defaults not changing.

Let's be brave and go forward with it. Let's go!

**Pull request merged**
