### PR TITLE
Fix NSS_VersionCheck("3.26") failed

### PR DESCRIPTION
**Pull request by stawidy**

### CODE REVIEW

**Comment by stawidy** [comment]
bot, build

**Comment by stawidy** [comment]
Reference https://github.com/flathub/com.valvesoftware.Steam/issues/47

**Comment by TingPing** [comment]
Actually I'm just going to add this to the electron base app since most Electron apps seem to need it the newer version now.

**Comment by stawidy** [comment]
Yes, it's a better way to fix this issue.

**Comment by TingPing** [comment]
I triggered a build with the new baseapp, let me know if there are any problems: https://flathub.org/builds/#/builders/2/builds/1698

**Comment by stawidy** [comment]
@TingPing it works well, thanks.

**Pull request closed without merging**
