### PR TITLE
Use Zypak for the sandbox

### PR DESCRIPTION
**Pull request by refi64**
**Do NOT merge this into master, please merge into a new beta branch instead!**

This PR adds support for keeping the sandbox via [zypak](https://github.com/refi64/zypak). Once everything is confirmed to be stable, I'll send another PR to a new zypak non-beta release, which should be ready to merge onto master. (You can also subscribe to release notifications for the zypak repository to watch future releases.)

### CODE REVIEW

**Comment by SISheogorath** [comment]
So I guess we should create a beta branch, if we want to merge that any time soon?

**Comment by refi64** [comment]
Yup!

**Comment by SISheogorath** [comment]
Here we go :) Do you happen to know if anything else is required for enabling proper beta channel support on Flathub? (changes in the flathub.json?)

**Comment by refi64** [comment]
From what I can tell, no, flathub should automatically build the branch as beta. (Based on [Godot's flathub.json](https://github.com/flathub/org.godotengine.Godot/blob/beta/flathub.json)).

**Comment by barthalion** [comment]
Yup, all is good. Closing PR.

**Pull request closed without merging**
