### PR TITLE
Update to 1.4.2

### PR DESCRIPTION
**Pull request by Erick555**
Not tested

### CODE REVIEW

**Comment by Erick555** [comment]
Flathub seems dead right now.

**Comment by SISheogorath** [comment]
@Erick555 can you push this once more?

**Comment by Erick555** [comment]
bot, build

**Comment by Erick555** [comment]
@SISheogorath re-pushing or restarting the build doesn't help. Flathub infra seems broken right now.

**Comment by SISheogorath** [comment]
Yeah, seems like that mhm, let's wait a while and then get things started :)

**Comment by SISheogorath** [comment]
bot, build

**Comment by SISheogorath** [comment]
Thanks!

**Pull request merged**
