### PR TITLE
Use static build instead of unpacking the deb

### PR DESCRIPTION
**Pull request by MatMaul**
~~It's unfortunately still crashing when using seshat for search in encrypted rooms :(
Next version of seshat should allow to build openssl statically too, let's see if it helps.~~

Search in encrypted rooms has been fixed !

### CODE REVIEW

**Comment by marc0x1** [comment]
does it works? does it needs testing?

**Comment by MatMaul** [comment]
It works, but I am waiting for the next release (1.11.31) because it should finally fixed the crashes when search in encrypted rooms is enabled :tada: 
In the meantime I would welcome a little feedback from @SISheogorath.

**Comment by SISheogorath** [comment]
I have had an eye on this PR since it was opened and was a bit cautious due to maintaining openssl on our own, but given that it is about to become bundled upstream with 1.11.31, I think this should become the new way to build Element soon :)

All in all, LGTM as soon as we get rid of OpenSSL :)

**Comment by MatMaul** [comment]
@SISheogorath I think we are finally good to go :)

**Comment by SISheogorath** [comment]
Great! Thank you for your work!

**Pull request merged**
